//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDienThoai_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSUDUNG
    {
        public int MACTSD { get; set; }
        public int MASIM { get; set; }
        public System.DateTime BATDAU { get; set; }
        public System.DateTime KETTHUC { get; set; }
        public Nullable<int> SOPHUTSUDUNG { get; set; }
        public Nullable<decimal> CUOCPHI { get; set; }
    
        public virtual THONGTINSIM THONGTINSIM { get; set; }
    }
}
