//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDienThoai_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIACUOC
    {
        public int MAGC { get; set; }
        public string TEN { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public Nullable<System.TimeSpan> APDUNGTU { get; set; }
        public Nullable<System.TimeSpan> APDUNGDEN { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    }
}
