//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDienThoai_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONTINHCUOC
    {
        public int MAHDTC { get; set; }
        public Nullable<int> MASIM { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> THANHTOAN { get; set; }
    
        public virtual THONGTINSIM THONGTINSIM { get; set; }
    }
}
