//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDienThoai_User.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCuocDienThoaiEntities : DbContext
    {
        public QLCuocDienThoaiEntities()
            : base("name=QLCuocDienThoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETSUDUNG> CHITIETSUDUNGs { get; set; }
        public virtual DbSet<GIACUOC> GIACUOCs { get; set; }
        public virtual DbSet<HOADONDANGKI> HOADONDANGKIs { get; set; }
        public virtual DbSet<HOADONTINHCUOC> HOADONTINHCUOCs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<THONGTINSIM> THONGTINSIMs { get; set; }
    }
}
