//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDienThoai_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINSIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINSIM()
        {
            this.CHITIETSUDUNGs = new HashSet<CHITIETSUDUNG>();
            this.HOADONDANGKIs = new HashSet<HOADONDANGKI>();
            this.HOADONTINHCUOCs = new HashSet<HOADONTINHCUOC>();
        }
    
        public int MASIM { get; set; }
        public string SODT { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSUDUNG> CHITIETSUDUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONDANGKI> HOADONDANGKIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTINHCUOC> HOADONTINHCUOCs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
