--- create the database ---
USE [master]
GO
DROP Database [QLCuocDienThoai]
GO
CREATE DATABASE [QLCuocDienThoai]
GO
--- create the tables ---

USE [QLCuocDienThoai]
GO
CREATE TABLE [KHACHHANG]
(
	[MAKH] [INT] NOT NULL IDENTITY(1,1),
	[TEN] [NVARCHAR](100),
	[THONGTIN] [NVARCHAR](100),
	[EMAIL] [NVARCHAR](100),
	[TINHTRANG] [INT],
	CONSTRAINT [PK_KHACHHANG] PRIMARY KEY ([MAKH])
)
GO
CREATE TABLE [GIACUOC]
(
	[MAGC] [INT] NOT NULL IDENTITY(1,1),
	[TEN] [NVARCHAR](100),
	[SOTIEN] [MONEY],
	[APDUNGTU] [TIME],
	[APDUNGDEN] [TIME],
	[TINHTRANG] [INT],
	CONSTRAINT [PK_GIACUOC] PRIMARY KEY ([MAGC])
)
CREATE TABLE [THONGTINSIM]
(
	[MASIM] [INT] NOT NULL IDENTITY(1,1),
	[SODT] [VARCHAR](10),
	[MAKH] [INT],
	[TINHTRANG] [INT],
	CONSTRAINT [PK_THONGTINSIM] PRIMARY KEY ([MASIM])
)
CREATE TABLE [HOADONDANGKI]
(
	[MAHDDK] [INT] NOT NULL IDENTITY(1,1),
	[MASIM] [INT],
	[PHIDANGKI] [MONEY],
	[NGAYDANGKI] [DATETIME]
	CONSTRAINT [PK_HOADONDANGKI] PRIMARY KEY ([MAHDDK])
)
CREATE TABLE [HOADONTINHCUOC]
(
	[MAHDTC] [INT] NOT NULL IDENTITY(1,1),
	[MASIM] [INT],
	[TONGTIEN] [MONEY],
	[THANG] [INT],
	[THANHTOAN] [INT],
	CONSTRAINT [PK_HOADONTINHCUOC] PRIMARY KEY ([MAHDTC])
)
CREATE TABLE [CHITIETSUDUNG]
(
	[MACTSD] [INT] NOT NULL IDENTITY(1,1),
	[MASIM] [INT] NOT NULL,
	[BATDAU] [DATETIME] NOT NULL,
	[KETTHUC] [DATETIME] NOT NULL,
	[SOPHUTSUDUNGSAU23H] [INT],
	[SOPHUTSUDUNGSAU7H] [INT],
	[CUOCPHI] [MONEY],
	CONSTRAINT [PK_SUDUNG] PRIMARY KEY ([MACTSD])
)
GO

--- Add the foreign key ---

ALTER TABLE [THONGTINSIM]
ADD CONSTRAINT [FK_THONGTINSIM_MAKH]
	FOREIGN KEY ([MAKH])
	REFERENCES [KHACHHANG]([MAKH])
GO
ALTER TABLE [HOADONDANGKI]
ADD CONSTRAINT [FK_HOADONDANGKI_MASIM]
	FOREIGN KEY ([MASIM])
	REFERENCES [THONGTINSIM]([MASIM])
GO
ALTER TABLE [HOADONTINHCUOC]
ADD CONSTRAINT [FK_HOADONTINHCUOC_MASIM]
	FOREIGN KEY ([MASIM])
	REFERENCES [THONGTINSIM]([MASIM])
GO
ALTER TABLE [CHITIETSUDUNG]
ADD CONSTRAINT [FK_CHITIETSUDUNG_MASIM]
	FOREIGN KEY ([MASIM])
	REFERENCES [THONGTINSIM]([MASIM])
GO

--- Insert the test data ---

INSERT INTO KHACHHANG(TEN,THONGTIN,EMAIL,TINHTRANG) 
	VALUES(N'Khách 1',N'Tên 1','khach1@gmail.com',1)
INSERT INTO KHACHHANG(TEN,THONGTIN,EMAIL,TINHTRANG) 
	VALUES(N'Khách 2',N'Tên 2','khach2@gmail.com',1)
INSERT INTO KHACHHANG(TEN,THONGTIN,EMAIL,TINHTRANG) 
	VALUES(N'Khách 3',N'Tên 3','khach3@gmail.com',1)

INSERT INTO GIACUOC(TEN,SOTIEN,APDUNGTU,APDUNGDEN,TINHTRANG)
	VALUES(N'Cước ngày',2000,'06:00:00','18:00:00',1)
INSERT INTO GIACUOC(TEN,SOTIEN,APDUNGTU,APDUNGDEN,TINHTRANG)
	VALUES(N'Cước đêm',1500,'18:00:00','01:00:00',1)
INSERT INTO GIACUOC(TEN,SOTIEN,APDUNGTU,APDUNGDEN,TINHTRANG)
	VALUES(N'Cước khuya',1000,'01:00:00','06:00:00',1)
	
INSERT INTO THONGTINSIM(SODT,MAKH,TINHTRANG)
	VALUES('1111111111',1,1)
INSERT INTO THONGTINSIM(SODT,MAKH,TINHTRANG)
	VALUES('2222222222',2,1)
INSERT INTO THONGTINSIM(SODT,MAKH,TINHTRANG)
	VALUES('3333333333',1,1)

INSERT INTO HOADONDANGKI(MASIM,PHIDANGKI,NGAYDANGKI)
	VALUES(1,50000,'11/24/2018 12:00:00')
INSERT INTO HOADONDANGKI(MASIM,PHIDANGKI,NGAYDANGKI)
	VALUES(2,50000,'11/24/2018 12:00:00')
INSERT INTO HOADONDANGKI(MASIM,PHIDANGKI,NGAYDANGKI)
	VALUES(3,50000,'11/25/2018 12:00:00')

--- show the tables ---

SELECT * FROM KHACHHANG;
GO
SELECT * FROM GIACUOC;
GO
SELECT * FROM THONGTINSIM;
GO
SELECT * FROM HOADONDANGKI;
GO
SELECT * FROM HOADONTINHCUOC;
GO
SELECT * FROM CHITIETSUDUNG;
GO

--- the end ---