--- create the database ---
USE [master]
GO
--DROP Database [QLCUOCDIENTHOAI]
GO
CREATE DATABASE [QLCUOCDIENTHOAI]
GO
--- create the tables ---

USE [QLCUOCDIENTHOAI]
GO
CREATE TABLE [KHACHHANG]
(
	[MAKH] [INT] NOT NULL IDENTITY(1,1),
	[TEN] [NVARCHAR](100),
	[THONGTIN] [NVARCHAR](100),
	[TINHTRANG] [INT],
	CONSTRAINT [PK_KHACHHANG] PRIMARY KEY ([MAKH])
)
GO
CREATE TABLE [SODIENTHOAI]
(
	[MADT] [INT] NOT NULL IDENTITY(1,1),
	[SODT] [VARCHAR](10),
	[THONGTIN] [NVARCHAR](100),
	[TINHTRANG] [INT],
	CONSTRAINT [PK_SODIENTHOAI] PRIMARY KEY ([MADT])
)
GO
CREATE TABLE [PHANPHOI]
(
	[MAPP] [INT] NOT NULL IDENTITY(1,1),
	[MAKH] [INT],
	[MADT] [INT],
	[THOIDIEMDANGKI] [DATETIME],
	[THOIDIEMKETTHUC] [DATETIME],
	CONSTRAINT [PK_PHANPHOI] PRIMARY KEY ([MAPP])
)
GO
CREATE TABLE [SUDUNG]
(
	[MASD] [INT] NOT NULL IDENTITY(1,1),
	[MADT] [INT],
	[BATDAU] [DATETIME],
	[KETTHUC] [DATETIME],
	CONSTRAINT [PK_SUDUNG] PRIMARY KEY ([MASD])
)
GO
CREATE TABLE [CUOCPHI]
(
	[MACC] [INT] NOT NULL IDENTITY(1,1),
	[TEN] [NVARCHAR](100),
	[SOTIEN] [MONEY],
	[APDUNGTU] [DATETIME],
	[APDUNGDEN] [DATETIME],
	CONSTRAINT [PK_CUOCPHI] PRIMARY KEY ([MACC])
)
GO
CREATE TABLE [HOADON]
(
	[MAHD] [INT] NOT NULL IDENTITY(1,1),
	[MAPP] [INT],
	[KI] [NVARCHAR](100),
	[TONGTIEN] [MONEY],
	[THANHTOAN] [INT]
	CONSTRAINT [PK_HOADON] PRIMARY KEY ([MAHD])
)
GO

--- Add the foreign key ---

ALTER TABLE [PHANPHOI]
ADD CONSTRAINT [FK_PHANPHOI_MAKH]
	FOREIGN KEY ([MAKH])
	REFERENCES [KHACHHANG]([MAKH])
GO
ALTER TABLE [PHANPHOI]
ADD CONSTRAINT [FK_PHANPHOI_MADT]
	FOREIGN KEY ([MADT])
	REFERENCES [SODIENTHOAI]([MADT])
GO
ALTER TABLE [SUDUNG]
ADD CONSTRAINT [FK_SUDUNG_MADT]
	FOREIGN KEY ([MADT])
	REFERENCES [SODIENTHOAI]([MADT])
GO
ALTER TABLE [HOADON]
ADD CONSTRAINT [FK_HOADON_MAPP]
	FOREIGN KEY ([MAPP])
	REFERENCES [PHANPHOI]([MAPP])
GO


--- Insert the test data ---

INSERT INTO KHACHHANG(TEN,THONGTIN,TINHTRANG) 
	VALUES(N'Khách 1',N'Tên 1',1)
INSERT INTO KHACHHANG(TEN,THONGTIN,TINHTRANG) 
	VALUES(N'Khách 2',N'Tên 2',1)
INSERT INTO KHACHHANG(TEN,THONGTIN,TINHTRANG) 
	VALUES(N'Khách 3',N'Tên 3',1)

INSERT INTO SODIENTHOAI(SODT,THONGTIN,TINHTRANG) 
	VALUES('1111111111',N'Số điện thoại 1',1)
INSERT INTO SODIENTHOAI(SODT,THONGTIN,TINHTRANG) 
	VALUES('2222222222',N'Số điện thoại 2',1)
INSERT INTO SODIENTHOAI(SODT,THONGTIN,TINHTRANG) 
	VALUES('3333333333',N'Số điện thoại 3',1)


--- show the tables ---

SELECT * FROM KHACHHANG;
GO
SELECT * FROM SODIENTHOAI;
GO
SELECT * FROM PHANPHOI;
GO
SELECT * FROM SUDUNG;
GO
SELECT * FROM CUOCPHI;
GO
SELECT * FROM HOADON;
GO

--- the end ---